{% set name = "apache-airflow-providers-ftp" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-ftp-{{ version }}.tar.gz
  sha256: de57a6cb29e4c57935e9380a8ea418221fab8f7543f6e50e81ec7de30b671293

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  imports:
    - airflow.providers.ftp
    - airflow.providers.ftp.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for File Transfer Protocol (FTP) for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-ftp/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
